FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -c "import nltk; nltk.download('vader_lexicon')"
COPY . .
EXPOSE 5050
CMD ["gunicorn", "-b", "0.0.0.0:5050", "app:app"]
